#!/usr/bin/env node
// Writes every opencaselaw.ch page in each of its languages as plain HTML.
//
//   node scripts/build_page_languages.mjs           write the pages
//   node scripts/build_page_languages.mjs --check   exit 1 if any page is not as it would be written
//
// The pages translate themselves in the browser: site.js fills every [data-t]
// element from the dictionary the page passes to OCL.init({i18n}). A search
// engine, a link preview or a reader without JavaScript got the same HTML for
// every ?lang=. This script renders that HTML once per language, from the same
// dictionaries, so the server has a page for each:
//
//   docs/citecheck/index.html       German, the page as edited (x-default)
//   docs/citecheck/fr/index.html    French, generated
//   docs/fr/methodology.html        a page at the top level: the language folder beside it
//
// Each page names the others (hreflang) and itself (canonical); its title and
// description are in its language (scripts/site_languages.json, else the
// headline and the lead paragraph). A page offers only the languages its
// dictionary has. The German page is rendered too, so what the server sends is
// what the page says it is. Edit the German page and its dictionary, then run
// this script; the test suite fails while a generated page is out of date.
// No dependencies: Node's vm reads the dictionaries.

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, statSync, unlinkSync, rmdirSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DOCS = join(ROOT, 'docs');
const SITE = 'https://opencaselaw.ch';
const LANGS = ['de', 'fr', 'it', 'rm', 'en'];
const SKIP = new Set(['404.html']);                 // GitHub Pages serves one 404, at the root
const MARK = '<!-- generated by scripts/build_page_languages.mjs';
const META = JSON.parse(readFileSync(join(ROOT, 'scripts/site_languages.json'), 'utf8'));
const VOID = new Set(['area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'link', 'meta', 'source', 'track', 'wbr']);

const escapeText = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const escapeAttr = (s) => escapeText(s).replace(/"/g, '&quot;');
const plain = (s) => String(s || '').replace(/<[^>]+>/g, ' ').replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/\s+/g, ' ').trim();

// ── the dictionaries ──────────────────────────────────────────────────────
// Anything a page script touches at load is a harmless stand-in; only OCL.init's argument matters.
const ANY = new Proxy(function () {}, {
  get: (t, k) => (k === Symbol.toPrimitive ? () => '' : k === Symbol.iterator ? function* () {} : ANY),
  apply: () => ANY, construct: () => ANY,
});

function dictionaries(html, file) {
  const after = html.slice(html.indexOf('/static/js/site.js'));
  const scripts = [...after.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g)].map((m) => m[1]);
  let options = null;
  const OCL = { init: (o) => { options = o; }, t: () => '', fmt: () => '', esc: (s) => s, lang: 'de', applyI18n: () => {} };
  const quiet = { log() {}, warn() {}, error() {}, info() {} };
  const ctx = { OCL, document: ANY, location: { search: '', pathname: '/', hash: '', href: SITE }, history: ANY,
    localStorage: { getItem: () => null, setItem() {} }, sessionStorage: { getItem: () => null, setItem() {} },
    fetch: () => new Promise(() => {}), console: quiet, setTimeout: () => 0, setInterval: () => 0, requestAnimationFrame: () => 0,
    URLSearchParams, URL, Intl, Date, Math, JSON, navigator: { language: 'de' }, IntersectionObserver: ANY, matchMedia: ANY };
  ctx.window = ctx;
  for (const s of scripts) {
    try { vm.runInNewContext(s, ctx, { timeout: 2000 }); } catch { /* a script that needs a real page; the dictionary does not */ }
  }
  if (!options || !options.i18n || !options.i18n.de) throw new Error(file + ': no OCL.init({i18n: {de: …}})');
  return JSON.parse(JSON.stringify(options.i18n));
}

const SHARED = (() => {
  const src = readFileSync(join(DOCS, 'static/js/site.js'), 'utf8');
  const m = /var SHARED = (\{[\s\S]*?\n {2}\});/.exec(src);
  return vm.runInNewContext('(' + m[1] + ')');
})();

// ── where each page and its languages live ────────────────────────────────
function pages() {
  const out = [];
  const visit = (dir) => {
    for (const name of readdirSync(dir)) {
      const path = join(dir, name);
      if (statSync(path).isDirectory()) { if (!LANGS.includes(name) && name !== 'static') visit(path); continue; }
      if (!name.endsWith('.html') || SKIP.has(relative(DOCS, path))) continue;
      const html = readFileSync(path, 'utf8');
      if (html.includes('OCL.init(') && !html.includes(MARK)) out.push(path);
    }
  };
  visit(DOCS);
  return out.sort();
}

// docs/citecheck/index.html -> /citecheck/ ; docs/methodology.html -> /methodology.html
const urlOf = (path) => '/' + relative(DOCS, path).split('\\').join('/').replace(/(^|\/)index\.html$/, '$1');
const fileFor = (base, lang) => (lang === 'de' ? base : join(dirname(base), lang, base.split(/[\\/]/).pop()));

// ── rendering ─────────────────────────────────────────────────────────────
// The [data-t] elements of the markup outside scripts and styles: [{key, start, end}] of
// their content, outermost only. A stray end tag closes nothing.
function translatableSpans(html) {
  const re = /<!--[\s\S]*?-->|<(script|style)\b[^>]*>[\s\S]*?<\/\1\s*>|<\/([a-zA-Z][\w-]*)\s*>|<([a-zA-Z][\w-]*)((?:"[^"]*"|'[^']*'|[^'">])*)>/g;
  const stack = [];
  const spans = [];
  let m;
  while ((m = re.exec(html)) !== null) {
    if (m[2]) {
      const name = m[2].toLowerCase();
      let at = stack.length - 1;
      while (at >= 0 && stack[at].name !== name) at--;
      if (at < 0) continue;
      const closing = stack.splice(at);
      const el = closing[0];
      if (el.key) spans.push({ key: el.key, start: el.inner, end: m.index });
      continue;
    }
    if (m[3]) {
      const name = m[3].toLowerCase();
      if (VOID.has(name) || /\/\s*$/.test(m[4])) continue;
      const key = /\sdata-t="([^"]+)"/.exec(m[4]);
      stack.push({ name, key: key && key[1], inner: m.index + m[0].length });
    }
  }
  return spans.filter((s) => !spans.some((o) => o !== s && o.start <= s.start && s.end <= o.end));
}

// A summary for <meta name="description">: the lead, cut at a sentence near 200 characters.
function summary(text) {
  const s = plain(text);
  if (s.length <= 200) return s;
  const stop = s.slice(0, 200).lastIndexOf('. ');
  if (stop > 80) return s.slice(0, stop + 1);
  return s.slice(0, s.lastIndexOf(' ', 196)) + ' …';
}

function setMeta(html, attr, name, value) {
  const re = new RegExp(`(<meta ${attr}="${name.replace(/[.:]/g, '\\$&')}" content=")[^"]*(")`);
  return re.test(html) ? html.replace(re, `$1${escapeAttr(value)}$2`) : html;
}

function render(source, { base, lang, langs, dict }) {
  const t = (key) => {
    for (const d of [dict[lang], dict.de, SHARED[lang], SHARED.de]) if (d && d[key] !== undefined) return d[key];
    return undefined;
  };
  let html = source;

  // 1. every [data-t] element, as site.js would fill it (markup where the text holds markup)
  for (const s of translatableSpans(html).sort((a, b) => b.start - a.start)) {
    const v = t(s.key);
    if (v === undefined) continue;
    const value = /<[a-z]/i.test(v) ? String(v) : escapeText(v);
    html = html.slice(0, s.start) + value + html.slice(s.end);
  }
  html = html.replace(/(<img\b[^>]*\salt=")[^"]*("[^>]*\sdata-t-alt="([^"]+)")/g, (all, a, b, key) => (t(key) === undefined ? all : a + escapeAttr(t(key)) + b));

  // 2. the head: language, title, description, canonical, the other languages
  const url = urlOf(base);
  const own = SITE + (lang === 'de' ? url : urlOf(fileFor(base, lang)));
  const meta = META[url] || {};
  const h1 = /<h1\b[^>]*\sdata-t="([^"]+)"/.exec(html);
  const lead = /class="page-lead"[^>]*\sdata-t="([^"]+)"|\sdata-t="([^"]+)"[^>]*class="page-lead"/.exec(html);
  const titleKey = /<title\b[^>]*\sdata-t="([^"]+)"/.exec(html);
  const title = (meta.title && meta.title[lang]) || (titleKey && plain(t(titleKey[1]))) || (h1 && t(h1[1]) !== undefined ? plain(t(h1[1])) + ' — OpenCaseLaw' : null);
  const description = (meta.description && meta.description[lang]) || (lead && t(lead[1] || lead[2]) !== undefined ? summary(t(lead[1] || lead[2])) : null);

  html = html.replace(/<html\b[^>]*>/, lang === 'de' ? '<html lang="de">' : `<html lang="${lang}" data-ocl-lang="${lang}">`);
  if (title) {
    html = html.replace(/(<title\b[^>]*>)[^<]*(<\/title>)/, `$1${escapeText(title)}$2`);
    html = setMeta(html, 'property', 'og:title', title);
    html = setMeta(html, 'name', 'twitter:title', title);
  }
  if (description) {
    html = setMeta(html, 'name', 'description', description);
    html = setMeta(html, 'property', 'og:description', description);
    html = setMeta(html, 'name', 'twitter:description', description);
  }
  html = setMeta(html, 'property', 'og:url', own);
  html = setMeta(html, 'property', 'og:locale', lang + '_CH');
  html = html.replace(/<meta property="og:locale:alternate" content="[^"]*">\n?/g, '');
  if (/<meta property="og:locale" /.test(html)) {
    const others = langs.filter((l) => l !== lang).map((l) => `<meta property="og:locale:alternate" content="${l}_CH">`).join('\n');
    html = html.replace(/(<meta property="og:locale" content="[^"]*">\n)/, `$1${others}\n`);
  }
  html = html.replace(/<link rel="alternate" hreflang="[^"]*" href="[^"]*">\n?/g, '');
  const alternates = [...langs.map((l) => `<link rel="alternate" hreflang="${l}" href="${SITE}${l === 'de' ? url : urlOf(fileFor(base, l))}">`),
    `<link rel="alternate" hreflang="x-default" href="${SITE}${url}">`].join('\n');
  html = html.replace(/<link rel="canonical" href="[^"]*">/, `<link rel="canonical" href="${own}">\n${alternates}`);

  // 3. a copy lives one folder down: its relative links and fetches point back up
  if (lang !== 'de') {
    const up = (v) => (/^(?:[a-z][a-z0-9+.-]*:|\/|#|\?|$)/i.test(v) ? v : '../' + v);
    html = html.replace(/<(script|style)\b[^>]*>[\s\S]*?<\/\1\s*>|<[a-zA-Z][^>]*>/g, (tag, block) => {
      if (block) return tag.replace(/\bfetch\((['"`])(?![a-z][a-z0-9+.-]*:|\/)/gi, 'fetch($1../');
      return tag.replace(/(\s(?:href|src|poster|action)=")([^"]*)(")/g, (all, a, v, b) => a + up(v) + b);
    });
    html = html.replace(/^(<!DOCTYPE html>\n?)/i, `$1${MARK} from ${relative(DOCS, base)}: edit that page and its dictionary, then run the script -->\n`);
  }
  return html;
}

// ── the sitemap: each page with its languages ─────────────────────────────
function sitemap(built) {
  const path = join(DOCS, 'sitemap.xml');
  const xml = readFileSync(path, 'utf8');
  const blocks = [...xml.matchAll(/ {2}<url>[\s\S]*?<\/url>\n/g)].map((m) => m[0]);
  const loc = (b) => (/<loc>([^<]*)<\/loc>/.exec(b) || [])[1];
  const ours = new Map(built.map((p) => [SITE + p.url, p]));
  const copies = new Set(built.flatMap((p) => p.langs.filter((l) => l !== 'de').map((l) => SITE + urlOf(fileFor(p.base, l)))));
  const kept = blocks.filter((b) => !copies.has(loc(b)));
  const out = [];
  const seen = new Set();
  const entry = (u, freq, prio, langs, base) => {
    let s = `  <url>\n    <loc>${u}</loc>\n    <changefreq>${freq}</changefreq>\n    <priority>${prio}</priority>\n`;
    if (langs) {
      for (const l of langs) s += `    <xhtml:link rel="alternate" hreflang="${l}" href="${SITE}${l === 'de' ? urlOf(base) : urlOf(fileFor(base, l))}" />\n`;
      s += `    <xhtml:link rel="alternate" hreflang="x-default" href="${SITE}${urlOf(base)}" />\n`;
    }
    return s + '  </url>\n';
  };
  const addPage = (p, freq, prio) => {
    out.push(entry(SITE + p.url, freq, prio, p.langs, p.base));
    const lower = Math.max(0.1, Math.round((Number(prio) - 0.1) * 10) / 10).toFixed(1);
    for (const l of p.langs) if (l !== 'de') out.push(entry(SITE + urlOf(fileFor(p.base, l)), freq, lower, p.langs, p.base));
    seen.add(SITE + p.url);
  };
  for (const b of kept) {
    const u = loc(b);
    const p = ours.get(u);
    if (!p) { out.push(b); continue; }
    addPage(p, (/<changefreq>([^<]*)/.exec(b) || [])[1] || 'weekly', (/<priority>([^<]*)/.exec(b) || [])[1] || '0.6');
  }
  for (const p of built) if (!seen.has(SITE + p.url)) addPage(p, 'weekly', '0.6');
  const head = xml.slice(0, xml.indexOf('  <url>'));
  return { path, text: head + out.join('') + '</urlset>\n' };
}

// ── main ──────────────────────────────────────────────────────────────────
const check = process.argv.includes('--check');
const writes = new Map();
const built = [];
for (const base of pages()) {
  const source = readFileSync(base, 'utf8');
  const dict = dictionaries(source, relative(ROOT, base));
  const langs = LANGS.filter((l) => dict[l]);
  built.push({ base, url: urlOf(base), langs });
  for (const lang of langs) writes.set(fileFor(base, lang), render(source, { base, lang, langs, dict }));
  // a language the page no longer has: its generated copy, or an old redirect to ?lang=, goes
  for (const lang of LANGS) {
    const f = fileFor(base, lang);
    if (lang === 'de' || langs.includes(lang) || !existsSync(f)) continue;
    const old = readFileSync(f, 'utf8');
    if (old.includes(MARK) || old.includes('location.replace(')) writes.set(f, null);
  }
}
const map = sitemap(built);
writes.set(map.path, map.text);

let stale = 0;
for (const [file, text] of writes) {
  const now = existsSync(file) ? readFileSync(file, 'utf8') : null;
  if (now === text) continue;
  stale++;
  if (check) { console.log('out of date: ' + relative(ROOT, file)); continue; }
  if (text === null) {
    unlinkSync(file);
    try { rmdirSync(dirname(file)); } catch { /* not empty */ }
  } else {
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, text);
  }
}
const copies = built.reduce((n, p) => n + p.langs.length - 1, 0);
console.log(`${built.length} pages, ${copies} language copies; ${stale} file${stale === 1 ? '' : 's'} ${check ? 'out of date' : 'written'}`);
process.exit(check && stale ? 1 : 0);
