#!/usr/bin/env python3
"""
check_intake_rates.py — per-court year-rate stale-intake detector.

The existing monitors watch the *scrape*: did the process exit 0, did the
portal answer, did our_count move. None of them watches the *corpus*: a feed
can die while every run reports success. Three silent deaths of exactly that
kind sat unnoticed in docs/coverage.json for months:

  - ow_gerichte:      0 rows since 2022 (the portal lists 4,035)
  - be_steuerrekurs:  0 rows since Feb 2026 (portal DB returns zero rows)
  - eight entscheidsuche-only feeds (be_bvd, be_weitere, sh_obergericht,
    tg_obergericht, sg_gerichte, sg_publikationen, vd_omni, vd_findinfo):
    0-2 rows dated 2026, plus ag_baugesetzgebung with no rows since 2021

This script reads docs/coverage.json (per-court `by_year`, regenerated by
publish step 5g) and compares the CURRENT year's row count with what the
previous two full years predict for the elapsed part of the year:

    expected = mean(rows[year-1], rows[year-2]) * elapsed_fraction
    ratio    = rows[year] / expected

    ratio < 0.25 -> STALE
    ratio < 0.60 -> LOW  (informational; does not affect the exit code)

Two special cases:

  * Silent courts (0 rows in BOTH previous full years) have no rate to
    compare against. They are STALE outright ("no rows since <last_year>"),
    provided the court once produced rows at all. This is the ow_gerichte
    shape.
  * Lagging courts. Some series carry decision dates far behind their
    publication date: BGE volume 152 (2026) already holds 104 decisions of
    which only 28 are *dated* 2026 (2026-09-09) — the official collection
    publishes 6-12 months after the judgment. For those, `lag_days` shifts
    the observation window: expected is pro-rated over
    max(0, elapsed_days - lag_days) instead of elapsed_days, and the court is
    reported WAIT (not judged) while that window is shorter than
    MIN_WINDOW_DAYS. bge is covered in the meantime by the corpus-growth
    stall detector in check_scraper_freshness.py (our_count, not dates).

Exemptions come ONLY from docs/intake_expected_stale.json (`expected_stale`).
A coverage note (docs/coverage_notes.json) is printed as context but does
not exempt: the notes for ow_gerichte and be_steuerrekurs describe outages
that are "re-probed weekly", and a detector that hides re-probed outages is
a detector that cannot tell you when the re-probe silently stopped working.
Courts that are stale BY DESIGN (abolished court, frozen archive, no new
volumes) belong in the JSON with a reason.

Exit code: 1 when any court that is not in `expected_stale` is STALE;
0 otherwise (LOW and WAIT never fail). --notify posts ONE ntfy message
(dedup-on-change with a daily re-nag, one all-clear on recovery, the
check_output_freshness.py pattern) via the same urllib POST that
dispatch_health_alerts.send uses. Sending is opt-in; the default run
only prints.

Usage:
    python3 scripts/check_intake_rates.py                  # table + exit code
    python3 scripts/check_intake_rates.py --only-flagged
    python3 scripts/check_intake_rates.py --as-of 2026-09-09 --coverage /path/coverage.json
    python3 scripts/check_intake_rates.py --notify         # also post to ntfy
    python3 scripts/check_intake_rates.py --json           # machine-readable rows

Manual invocation this week (no timer): see docs/observability.md,
"Per-court intake rate".
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import urllib.request
from dataclasses import asdict, dataclass
from datetime import date, datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DEFAULT_COVERAGE = REPO / "docs" / "coverage.json"
DEFAULT_POLICY = REPO / "docs" / "intake_expected_stale.json"
DEFAULT_STATE = Path(os.environ.get(
    "INTAKE_RATES_STATE", str(REPO / "logs" / "intake_rates_state.json")))

# Env-driven like check_scraper_freshness.py / check_output_freshness.py (one
# operator topic via NTFY_TOPIC in /opt/caselaw/ops.env); the scrapers topic
# is the fallback because a dead feed is a scraper matter.
NTFY_URL = (
    os.environ.get("NTFY_URL", "https://ntfy.sh").rstrip("/")
    + "/"
    + os.environ.get("NTFY_TOPIC", "opencaselaw-scrapers")
)

STALE_RATIO = 0.25
LOW_RATIO = 0.60
MIN_ROWS = 100          # courts below this are too small to judge by rate
MIN_EXPECTED = 5.0      # pro-rated expectation below this is noise (eschk: 2, 1 rows/yr)
MIN_WINDOW_DAYS = 30    # after the lag shift, judge only on at least a month of window
RENAG_HOURS = 24.0

STATUS_ORDER = {"STALE": 0, "LOW": 1, "OK": 2, "WAIT": 3, "EXPECTED": 4, "NEW": 5, "SMALL": 6}


@dataclass
class Row:
    court: str
    status: str            # STALE | LOW | OK | WAIT | EXPECTED | NEW | SMALL
    total: int
    current: int           # rows dated in the current year
    prev1: int             # rows dated year-1
    prev2: int             # rows dated year-2
    expected: float | None  # pro-rated expectation (None when undefined)
    ratio: float | None
    shortfall: float       # expected - current (0 when undefined)
    last_year: str | None
    lag_days: int
    reason: str            # "no rows since 2022", the expected_stale reason, ...
    note: str | None       # coverage note, context only

    def line(self) -> str:
        exp = f"{self.expected:7.1f}" if self.expected is not None else "      -"
        rat = f"{self.ratio:5.2f}" if self.ratio is not None else "    -"
        reason = self.reason
        if self.note and self.status in ("STALE", "LOW"):
            reason = (reason + "; " if reason else "") + "note: " + self.note[:70]
        return (f"{self.status:8} {self.court:32} {rat} {self.current:6} /{exp}"
                f" {self.prev2:6} {self.prev1:6}  {self.last_year or '-':>4}  {reason}")


def _days_in_year(year: int) -> int:
    return 366 if (year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)) else 365


def elapsed_days(as_of: date) -> int:
    """Days of the year elapsed at as_of, inclusive (Jan 1 -> 1)."""
    return as_of.timetuple().tm_yday


def load_policy(path: Path | None) -> dict:
    """{'expected_stale': {court: reason}, 'lag_days': {court: int}}."""
    policy = {"expected_stale": {}, "lag_days": {}}
    if path is None or not path.exists():
        return policy
    raw = json.loads(path.read_text())
    for court, val in (raw.get("expected_stale") or {}).items():
        policy["expected_stale"][court] = val.get("reason", "") if isinstance(val, dict) else str(val)
    for court, val in (raw.get("lag_days") or {}).items():
        days = val.get("days") if isinstance(val, dict) else val
        policy["lag_days"][court] = int(days)
    return policy


def as_of_from_coverage(cov: dict) -> date:
    gen = (cov.get("generated_at") or "")[:10]
    try:
        return date.fromisoformat(gen)
    except ValueError:
        return datetime.now(timezone.utc).date()


def evaluate(cov: dict, policy: dict, as_of: date, *,
             stale_ratio: float = STALE_RATIO, low_ratio: float = LOW_RATIO,
             min_rows: int = MIN_ROWS, min_expected: float = MIN_EXPECTED) -> list[Row]:
    """Pure: coverage dict + policy + date -> rows sorted by shortfall."""
    year = as_of.year
    elapsed = elapsed_days(as_of)
    diy = _days_in_year(year)
    expected_stale = policy.get("expected_stale", {})
    lag_table = policy.get("lag_days", {})
    rows: list[Row] = []

    for c in cov.get("courts", []):
        court = c.get("court")
        if not court:
            continue
        total = int(c.get("total") or 0)
        by_year = {str(k): int(v) for k, v in (c.get("by_year") or {}).items()}
        cur = by_year.get(str(year), 0)
        p1 = by_year.get(str(year - 1), 0)
        p2 = by_year.get(str(year - 2), 0)
        years_with_rows = sorted(y for y, n in by_year.items() if n > 0)
        last_year = years_with_rows[-1] if years_with_rows else None
        lag = int(lag_table.get(court, 0))
        note = c.get("note")
        base = {"court": court, "total": total, "current": cur, "prev1": p1, "prev2": p2,
                "last_year": last_year, "lag_days": lag, "note": note}

        if total < min_rows:
            rows.append(Row(status="SMALL", expected=None, ratio=None, shortfall=0.0,
                            reason=f"{total} rows < {min_rows}", **base))
            continue

        window = max(0, elapsed - lag)
        mean_prev = (p1 + p2) / 2.0

        if mean_prev == 0:
            # No rate to compare against. Either the court is new this year
            # (rows now, none before) or it has gone silent.
            if cur > 0 or last_year is None:
                rows.append(Row(status="NEW", expected=None, ratio=None, shortfall=0.0,
                                reason="no rows in the two previous years", **base))
                continue
            # Silent: pro-rate the last two years that had rows, so the row
            # sorts by what the court used to deliver.
            tail = [by_year[y] for y in years_with_rows[-2:]]
            expected = (sum(tail) / len(tail)) * window / diy
            status = "EXPECTED" if court in expected_stale else "STALE"
            reason = expected_stale.get(court) if status == "EXPECTED" else f"no rows since {last_year}"
            rows.append(Row(status=status, expected=expected, ratio=0.0,
                            shortfall=expected, reason=reason or "", **base))
            continue

        expected = mean_prev * window / diy
        if window < MIN_WINDOW_DAYS:
            rows.append(Row(status="WAIT", expected=expected, ratio=None, shortfall=0.0,
                            reason=f"lag {lag}d leaves a {window}d window (< {MIN_WINDOW_DAYS}d)",
                            **base))
            continue
        if expected < min_expected:
            rows.append(Row(status="SMALL", expected=expected, ratio=None, shortfall=0.0,
                            reason=f"expected {expected:.1f} < {min_expected:g}", **base))
            continue
        ratio = cur / expected
        if court in expected_stale:
            status, reason = "EXPECTED", expected_stale[court]
        elif ratio < stale_ratio:
            status, reason = "STALE", f"{cur} of {expected:.0f} expected"
        elif ratio < low_ratio:
            status, reason = "LOW", f"{cur} of {expected:.0f} expected"
        else:
            status, reason = "OK", ""
        rows.append(Row(status=status, expected=expected, ratio=ratio,
                        shortfall=max(0.0, expected - cur), reason=reason, **base))

    rows.sort(key=lambda r: (STATUS_ORDER.get(r.status, 9),
                             r.ratio if r.ratio is not None else 9.0,
                             -r.shortfall, r.court))
    return rows


def flagged(rows: list[Row]) -> tuple[list[Row], list[Row]]:
    """(stale rows that fail the run, low rows) — EXPECTED never fails."""
    stale = [r for r in rows if r.status == "STALE"]
    low = [r for r in rows if r.status == "LOW"]
    return stale, low


def format_table(rows: list[Row], as_of: date, only_flagged: bool = False) -> str:
    header = (f"{'status':8} {'court':32} ratio    cur/expected  {'y-2':>6} {'y-1':>6}  last  reason\n"
              f"(as of {as_of.isoformat()}, day {elapsed_days(as_of)} of {_days_in_year(as_of.year)}; "
              f"STALE < {STALE_RATIO:g}, LOW < {LOW_RATIO:g}, courts >= {MIN_ROWS} rows)")
    body = [r.line() for r in rows
            if not only_flagged or r.status in ("STALE", "LOW", "WAIT")]
    return "\n".join([header, *body])


def summary_line(stale: list[Row], low: list[Row]) -> str:
    """The one ntfy line: every STALE court with its reason, LOW as a count."""
    parts = [f"{r.court} ({r.reason})" for r in stale]
    msg = f"STALE intake ({len(stale)}): " + ", ".join(parts) if stale else "no STALE intake"
    if low:
        msg += f"; LOW ({len(low)}): " + ", ".join(r.court for r in low)
    return msg


def post_ntfy(title: str, message: str, priority: str = "default",
              tags: str = "warning", url: str | None = None) -> bool:
    """Same mechanism as dispatch_health_alerts.send: urllib POST with
    Title / Priority / Tags headers. Title is ASCII-cleaned because urllib
    encodes headers latin-1 and court notes carry em-dashes."""
    req = urllib.request.Request(
        url or NTFY_URL, data=message.encode("utf-8", errors="replace"),
        headers={"Title": title.encode("ascii", errors="replace").decode("ascii"),
                 "Priority": priority, "Tags": tags},
    )
    try:
        urllib.request.urlopen(req, timeout=10).read()
        return True
    except Exception as e:  # noqa: BLE001
        print(f"ntfy send failed: {e}", file=sys.stderr)
        return False


def _digest(rows: list[Row]) -> str:
    keys = sorted(f"{r.court}:{r.status}" for r in rows if r.status in ("STALE", "LOW"))
    return hashlib.sha256("\n".join(keys).encode()).hexdigest()


def maybe_notify(rows: list[Row], now: datetime, state_path: Path,
                 renag_hours: float = RENAG_HOURS, sender=post_ntfy) -> str:
    """Dedup-on-change + re-nag + one all-clear. Returns what happened."""
    stale, low = flagged(rows)
    prev: dict = {}
    if state_path.exists():
        try:
            prev = json.loads(state_path.read_text())
        except Exception:  # noqa: BLE001
            prev = {}

    if not stale:
        if prev.get("digest"):
            sender("OpenCaseLaw intake all-clear", "no court is STALE any more",
                   tags="white_check_mark")
            try:
                state_path.unlink()
            except OSError:
                pass
            return "all-clear"
        return "ok"

    digest = _digest(rows)
    last = prev.get("dispatched_at")
    try:
        last_dt = datetime.fromisoformat(last) if last else None
    except ValueError:
        last_dt = None
    renag = last_dt is not None and (now - last_dt).total_seconds() >= renag_hours * 3600
    if digest == prev.get("digest") and not renag:
        return "unchanged"
    ok = sender(f"OpenCaseLaw intake: {len(stale)} STALE, {len(low)} LOW",
                summary_line(stale, low), priority="high", tags="rotating_light")
    if not ok:
        return "post-failed"
    try:
        state_path.parent.mkdir(parents=True, exist_ok=True)
        tmp = state_path.with_suffix(".tmp")
        tmp.write_text(json.dumps({"digest": digest, "dispatched_at": now.isoformat(),
                                   "stale": [r.court for r in stale],
                                   "low": [r.court for r in low]}, indent=1))
        os.replace(tmp, state_path)
    except OSError as e:
        print(f"state write failed: {e}", file=sys.stderr)
    return "posted"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--coverage", default=str(DEFAULT_COVERAGE))
    ap.add_argument("--policy", default=str(DEFAULT_POLICY),
                    help="JSON with expected_stale + lag_days (default docs/intake_expected_stale.json)")
    ap.add_argument("--as-of", default=None,
                    help="YYYY-MM-DD; default = coverage.json generated_at, so a stale snapshot "
                         "is judged against its own date, not today's")
    ap.add_argument("--only-flagged", action="store_true", help="print STALE/LOW/WAIT rows only")
    ap.add_argument("--json", action="store_true", help="print rows as JSON instead of the table")
    ap.add_argument("--notify", action="store_true", help="post one ntfy line (opt-in)")
    ap.add_argument("--state-file", default=str(DEFAULT_STATE))
    ap.add_argument("--renag-hours", type=float, default=RENAG_HOURS)
    a = ap.parse_args(argv)

    cov = json.loads(Path(a.coverage).read_text())
    policy = load_policy(Path(a.policy) if a.policy else None)
    as_of = date.fromisoformat(a.as_of) if a.as_of else as_of_from_coverage(cov)
    rows = evaluate(cov, policy, as_of)
    stale, low = flagged(rows)

    if a.json:
        print(json.dumps({"as_of": as_of.isoformat(), "rows": [asdict(r) for r in rows]},
                         indent=1, ensure_ascii=False))
    else:
        print(format_table(rows, as_of, only_flagged=a.only_flagged))
        print()
        print(summary_line(stale, low))

    if a.notify:
        print(f"ntfy: {maybe_notify(rows, datetime.now(timezone.utc), Path(a.state_file), a.renag_hours)}")
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
